fos_elastica:
    clients:
        default: {
            url: 'elasticsearch:9200/',
            username: 'elastic',
            password: 'elastic'
        }
    indexes:
        mskguru: ~
        developers: ~